services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 5s
      timeout: 3s
      retries: 5

  cassandra:
    image: cassandra:latest
    container_name: great_jennings
    ports:
      - "9142:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - rag_network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    container_name: ragagentbot-backend
    build:
      context: ./ragagent/backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ragagent/backend/app:/app 
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CASSANDRA_HOSTS=great_jennings
    depends_on:
      cassandra:
        condition: service_healthy

    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

volumes:
  ollama_data:
  cassandra_data: