version: "3.9"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9142:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - ragnet
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  ragagentbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ragagentbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models 
      - ./backend/APP:/app  # Mount the backend code for live editing
      - ./frontend:/app/frontend  # Mount the frontend code for live editing
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - ragnet
    restart: always



  streamlit:
    build:
      context: .
    container_name: streamlit
    command: streamlit run streamlit_app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - ragagentbot
    networks:
      - ragnet

#  streamlit_dashboard:
#    build:
#      context: .
#    container_name: streamlit_dashboard
#    command: streamlit run dashboard.py --server.port 8502
#    ports:
#      - "8502:8502"
#    env_file:
#      - .env
#    volumes:
#      - ./ragagent:/app
#    depends_on:
#      - ragagentbot
#    networks:
#      - ragnet

networks:
  ragnet:
    driver: bridge

volumes:
  cassandra-data:
    driver: local
