
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9142:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - cassandra-net
    restart: always

  ragagentbot:
    build:
      context: .         # root of ragagent/
      dockerfile: Dockerfile
    container_name: ragagentbot
    hostname: ragagentbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - cassandra
    networks:
      - cassandra-net

  streamlit:
    build:
      context: .
    container_name: streamlit
    command: streamlit run streamlit_app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - ragagentbot
    networks:
      - cassandra-net


networks:
  cassandra-net:
    driver: bridge

volumes:
  cassandra-data:
    driver: local
